### ISSUE TITLE
[BUG] - How to force recharge when in FAULT mode?

### ISSUE THREAD

**Issue by emmanuelbarraud** [dalathegreat/Battery-Emulator#1799]
Hello,

I have a (normally) successful setup with Fronuis GEN24 and Renault Zoé v1 battery (by the way, huge thanks @dalathegreat for the tutorial 👍 ). It's been up for >6 months.

However it sometimes happens that the battery discharges too much.

I have "min 7% SoC limit" in the Fronius configuration and "min SoC 10%" with "scaled SoC" activated in battery emulator. So officially I should never go below 17% "real SoC" according to the emulator.

But it still happens sometimes – and now I have reached a real SoC of 3,9%, with a high cell delta and all cells below 3V, resulting that the Emulator is in "FAULT" mode. 

<img width="709" height="1095" alt="Image" src="https://github.com/user-attachments/assets/c82b9327-b58d-41ab-8ca6-06ce2eaf120d" />

The Fronius interface thus sees the battery as "Disabled" – so the "forced recharge" tricks on inverter do not catch up.

Any clue on how I could bypass the "FAULT" diagnostic to enable forced recharge? Or any other suggestion?

Many, many thanks!

**Comment by dalathegreat** [comment]
I noticed that Fronius changed how their software works. Previously it would enter force charge if your SOC% was 0%, but now you need to send a few % in order to get it to charge.

You can workaround this by setting negatively scaled SOC%, 

<img width="333" height="85" alt="Image" src="https://github.com/user-attachments/assets/8a9e7848-d269-4ca8-843a-7daceb83650e" />

This should allow the code to send a few % to get charging going

Oh, and you need to clear the  FAULT, but it looks like the overdischarge protection kicked  in and opened contactors. This is quite tricky to recover from, since you might need to compile custom FW with lower limits. It is a quite long project to recover an overdischarged battery, but you might be able to clear limit and quickly start charging to boost voltages up above limits

Finally, software 8.9 is no longer supported. Please update to the latest 9.2.3 version!

**Comment by emmanuelbarraud** [comment]
Thank you for being so incredibly reactive. I've tried to update but got some issues flashing the code to the Liligo from a Mac. Will try OTA. 

8.9 doesn't seem to allow a negative min SoC. Yet, Fronius "sees" 4% if I remove the "scaled SoC" option – but it still doesn't allow recharge (probably blocked by the "fault" status). 

The "solution" I used earlier was to connect the battery directly to the solar field – it recharged indeed, but it isn't very protocolar.

**Comment by dalathegreat** [comment]
You cannot OTA from 8.9 (it does not have correct partition layout), you will have to do the USB initial setup like shown in the Quickstart guide: https://youtu.be/sR3t7j0R9Z0

Updating to the latest version should solve the undercharge issue completely, since we have new safeties implemented to avoid getting stuck in this state

**Comment by emmanuelbarraud** [comment]
Good to know! I will try, huge thanks.

**Comment by emmanuelbarraud** [comment]
Thank you again Dala. Update to 9.2.4 eventually worked (my issue was an inappropriate cable), in turn I could update the inverter. Still not enough, though, to force recharge. "Too low DC power for feed-in", says the inverter, and the status of the emulator is still FAULT.

<img width="719" height="747" alt="Image" src="https://github.com/user-attachments/assets/10be73aa-72fd-4b80-b3e4-2a1ace9b5988" />

My guess is that the Fault is because of the cell delta rather than the overall voltage (I lowered the "Target discharge voltage" to 230, but to no avail).

**Comment by dalathegreat** [comment]
Try to OTA update to this version, to momentarily allow charge:

EDIT: File removed, unsafe situation over.

You need to get voltage up ASAP, you are risking permanent cell damage

**Comment by emmanuelbarraud** [comment]
Thanks! Done, but I cannot get out of the "FAULT" mode... and the battery is still seen in "energy saving mode", so it doesn't charge.

I know that my cells are at risk... I'll do my "hack" tomorrow.

**Comment by dalathegreat** [comment]
Use the Events page to see which Event is causing FAULT

**Comment by emmanuelbarraud** [comment]
Here... it doesn't look too good! Really strange because the cells are way to _low_, not high...
<img width="688" height="493" alt="Image" src="https://github.com/user-attachments/assets/c6ae49c0-8bf9-4af4-a38f-7936d6285854" />

<img width="403" height="528" alt="Image" src="https://github.com/user-attachments/assets/81c0d83e-f223-4c39-945e-0e06697f50b4" />

Note: 19.00 is when I tried to unplug the 12V supply to the battery (hoping to have it restarted in some way). It may have confused the sensors...

**Comment by dalathegreat** [comment]
You can press the Clear Events button to have it try again. Values get corrupted if you remove 12V.

I really think you need to charge NOW to avoid a permanently destroyed battery. Also charging a cell at 1.9V is DANGEROUS. You need to restrict charge power to not tear apart the cell physically. Charge only 1A.

**Comment by emmanuelbarraud** [comment]
Daniel, you really are a genius! 

<img width="434" height="393" alt="Image" src="https://github.com/user-attachments/assets/b7766dd1-7bfe-4cc7-916e-b33877a6fe33" />

Now slowly charging at 1.0A. I will let it run like that until it reaches 30%. 

<img width="700" height="391" alt="Image" src="https://github.com/user-attachments/assets/7f74df4f-a0ed-47bf-9657-ed063fa89625" />

Thank you again for your help and sorry for having taken so much of your time!

**Comment by dalathegreat** [comment]
Phew, I was getting really anxious seeing that low voltage 😅 Keep a close eye on the battery, and please revert to the Default 9.2.4 firmware when the battery is back in allowed voltage range (>3.1 cellvoltage)

**Comment by emmanuelbarraud** [comment]
Will do. Big kudos for all your work !!

**Comment by dalathegreat** [comment]
Again want to stress the importance of keeping close eye on this battery after this event. Recovering a lithium ion cell from an overdischarge scenario does not come without risks. These cells that dipped low will now be lower capacity than the rest of the system, and in a worst case scenario they will be so damaged that they heat up faster than the rest of the battery. Having tried 18650 recovery myself for years, it is borderline impossible to revive a <1.0V cell, and the success rate for <2.0v cells are low, and can result in high IR cells that really heat up significantly during charge/discharge.

If you have access to a thermal camera, do use it. And think really carefully about the placement of this battery. The risk of it going up in flames has now risen significantly.

Normally we say "game over" if a Zoe battery goes below 2.7v, and I really hoped your battery would have stopped at 2.1V, but when I saw that 1.9V it really hurt my stomach. Pay very close attention to the battery @emmanuelbarraud ⚠️ 

As one person on the Discord said;
_So I'd say: lesson learned the hard way, dispose battery and start over.
And only keep using this battery if it can safely burn down without impacting anything as should it decide to do so._

**Comment by dalathegreat** [comment]
Closing this issue as completed. Sidenote, we deployed Fronius specific fixes in [v9.3.0](https://github.com/dalathegreat/Battery-Emulator/pull/1805) that makes it harder to get a Fronius inverter result in undercharged batteries. Might be a good idea to take it into use!
